- name: Credit card number
  severity: info
  type: pattern
  values:
    - (?<!([0-9]\.|[=*+\/\-] |.[=*+\/\-]))((?<![0-9A-Za-z_=*+\-\/.])(?P<value>[0-9]{16})(?![0-9A-Za-z_=*+\-\/.]))(?!(\.[0-9]| [=*+\/\-]|.[=*+\/\-]))
  filter_type: CreditCardNumberSequence
  use_ml: false
  validations: []
  min_line_len: 16
  usage_list:
    - src

- name: API
  severity: medium
  type: keyword
  values:
    - api
  filter_type: GeneralKeyword
  use_ml: true
  validations: []
  required_substrings:
    - api
  usage_list:
    - src

- name: AWS Client ID
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>(ABIA|ACCA|AGPA|AIDA|AIPA|AKIA|ANPA|ANVA|AROA|APKA|ASCA|ASIA)[0-9A-Z]{16,17})([^0-9A-Za-z]|$)
  filter_type: GeneralPattern
  use_ml: true
  validations: []
  required_substrings:
    - A
  min_line_len: 20
  usage_list:
    - src
    - doc

- name: AWS Multi
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>(AKIA|ASIA)[0-9A-Z]{16,17})([^0-9A-Za-z]|$)
    - (?P<value>[0-9a-zA-Z/+]{40})
  filter_type: GeneralPattern
  use_ml: true
  validations: []
  required_substrings:
    - AKIA
    - ASIA
  min_line_len: 20
  usage_list:
    - src
    - doc

- name: AWS MWS Key
  severity: high
  type: pattern
  values:
    - (?P<value>amzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})
  filter_type: GeneralPattern
  use_ml: true
  validations: []
  required_substrings:
    - amzn
  min_line_len: 30
  usage_list:
    - src
    - doc

- name: Credential
  severity: medium
  type: keyword
  values:
    - credential
  filter_type: GeneralKeyword
  use_ml: true
  validations: []
  required_substrings:
    - credential
  usage_list:
    - src

- name: Dynatrace API Token
  severity: high
  type: pattern
  values:
    - (?P<value>dt0[a-zA-Z]{1}[0-9]{2}\.[A-Z0-9]{24}\.[A-Z0-9]{64})
  filter_type: GeneralPattern
  use_ml: true
  validations: []
  required_substrings:
    - dt0
  min_line_len: 90
  usage_list:
    - src
    - doc

- name: Facebook Access Token
  severity: high
  type: pattern
  values:
    - (?P<value>EAACEdEose0cBA[0-9A-Za-z]+)
  filter_type: GeneralPattern
  use_ml: true
  validations: []
  required_substrings:
    - EAACEdEose0cBA
  min_line_len: 15
  usage_list:
    - src
    - doc

- name: Github Old Token
  severity: high
  type: pattern
  values:
    - (?i)((git)[\w\-]*(token|key|api)[\w\-]*(\s)*(=|:|:=)(\s)*(["']?)(?P<value>[a-z|\d]{40})(["']?))
  filter_type: GeneralPattern
  use_ml: true
  validations:
    - GithubTokenValidation
  required_substrings:
    - git
  min_line_len: 47
  usage_list:
    - src
    - doc

- name: Google API Key
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>AIza[0-9A-Za-z\-_]{35})([^0-9A-Za-z]|$)
  filter_type: GeneralPattern
  use_ml: true
  validations:
    - GoogleApiKeyValidation
  required_substrings:
    - AIza
  min_line_len: 39
  usage_list:
    - src
    - doc

- name: Google Multi
  severity: high
  type: pattern
  values:
    - (?P<value>[0-9]+\-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com)
    - (?<![0-9a-zA-Z_-])(?P<value>[0-9a-zA-Z_-]{24})([^0-9A-Za-z]|$)
  filter_type: GeneralPattern
  use_ml: true
  validations:
    - GoogleMultiValidation
  required_substrings:
    - googleusercontent
  min_line_len: 40
  usage_list:
    - src
    - doc

- name: Google OAuth Access Token
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>ya29\.[0-9A-Za-z\-_]+)
  filter_type: GeneralPattern
  use_ml: true
  validations: []
  required_substrings:
    - ya29.
  min_line_len: 6
  usage_list:
    - src
    - doc

- name: Heroku API Key
  severity: high
  type: pattern
  values:
    - (?P<value>(?i)heroku(.{0,20})?[0-9a-f]{8}(-[0-9a-f]{4})+-[0-9a-f]{12})
  filter_type: GeneralPattern
  use_ml: true
  validations: []
  required_substrings:
    - heroku
  min_line_len: 24
  usage_list:
    - src
    - doc

- name: Instagram Access Token
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>IGQVJ[\w]{100,})
  filter_type: GeneralPattern
  use_ml: true
  validations: []
  required_substrings:
    - IGQVJ
  min_line_len: 105
  usage_list:
    - src
    - doc

- name: JSON Web Token
  severity: medium
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>eyJ[A-Za-z0-9-_=]+(\.[A-Za-z0-9-_.+\/=]+)?)
  filter_type: GeneralPattern
  use_ml: true
  validations: []
  required_substrings:
    - eyJ
  min_line_len: 9
  usage_list:
    - src
    - doc

- name: MailChimp API Key
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>[0-9a-f]{32}-us[0-9]{1,2})
  filter_type: GeneralPattern
  use_ml: true
  validations:
    - MailChimpKeyValidation
  required_substrings:
    - -us
  min_line_len: 35
  usage_list:
    - src
    - doc

- name: MailGun API Key
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>key-[0-9a-zA-Z]{32})([^0-9A-Za-z]|$)
  filter_type: GeneralPattern
  use_ml: true
  validations: []
  required_substrings:
    - key-
  min_line_len: 36
  usage_list:
    - src
    - doc

- name: Password
  severity: medium
  type: keyword
  values:
    - pass|pwd
  filter_type: PasswordKeyword
  use_ml: true
  validations: []
  required_substrings:
    - pass
    - pwd
  usage_list:
    - src

- name: PayPal Braintree Access Token
  severity: high
  type: pattern
  values:
    - (?P<value>access_token\$production\$[0-9a-z]{16}\$[0-9a-f]{32})
  filter_type: GeneralPattern
  use_ml: true
  validations: []
  required_substrings:
    - access_token
  min_line_len: 72
  usage_list:
    - src
    - doc

- name: PEM Certificate
  severity: high
  type: pem_key
  values:
    - (?P<value>-----BEGIN\s(?!ENCRYPTED|EC).*PRIVATE)
  filter_type: PEMPattern
  use_ml: false
  validations: []
  usage_list:
    - src

- name: Picatic API Key
  severity: high
  type: pattern
  values:
    - (?P<value>sk_live_[0-9a-z]{32})
  filter_type: GeneralPattern
  use_ml: true
  validations: []
  required_substrings:
    - sk_live_
  min_line_len: 40
  usage_list:
    - src
    - doc

- name: Secret
  severity: medium
  type: keyword
  values:
    - secret
  filter_type: GeneralKeyword
  use_ml: true
  validations: []
  required_substrings:
    - secret
  usage_list:
    - src

- name: SendGrid API Key
  severity: high
  type: pattern
  values:
    - (?P<value>SG\.[\w_]{16,32}\.[\w_]{16,64})
  filter_type: GeneralPattern
  use_ml: true
  validations: []
  required_substrings:
    - SG.
  min_line_len: 34
  usage_list:
    - src
    - doc

- name: Shopify Token
  severity: high
  type: pattern
  values:
    - (?P<value>shp(at|ca|pa|ss)_[a-fA-F0-9]{32})
  filter_type: TokenPattern
  use_ml: false
  validations: []
  required_substrings:
    - shp
  min_line_len: 38
  usage_list:
    - src
    - doc

- name: Slack Token
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>xox[a|b|p|r|o|s]\-[-a-zA-Z0-9]{10,250})
  filter_type: GeneralPattern
  use_ml: true
  validations:
    - SlackTokenValidation
  required_substrings:
    - xox
  min_line_len: 15
  usage_list:
    - src
    - doc

- name: Slack Webhook
  severity: high
  type: pattern
  values:
    - (?P<value>hooks\.slack\.com/services/T\w{8}/B\w{8}/\w{24})
  filter_type: GeneralPattern
  use_ml: true
  validations: []
  required_substrings:
    - slack
  min_line_len: 61
  usage_list:
    - src
    - doc

- name: Stripe Standard API Key
  severity: high
  type: pattern
  values:
    - (?P<value>sk_live_[0-9a-zA-Z]{24})
  filter_type: GeneralPattern
  use_ml: true
  validations:
    - StripeApiKeyValidation
  required_substrings:
    - sk_live_
  min_line_len: 32
  usage_list:
    - src
    - doc

- name: Stripe Restricted API Key
  severity: high
  type: pattern
  values:
    - (?P<value>rk_live_[0-9a-zA-Z]{24})
  filter_type: GeneralPattern
  use_ml: true
  validations: []
  required_substrings:
    - rk_live_
  min_line_len: 32
  usage_list:
    - src
    - doc

- name: Square Access Token
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>EAAA[0-9A-Za-z\-_]{60})([^0-9A-Za-z]|$)
  filter_type: GeneralPattern
  use_ml: true
  validations:
    - SquareAccessTokenValidation
  required_substrings:
    - EAAA
  min_line_len: 64
  usage_list:
    - src
    - doc

- name: Square Client ID
  severity: medium
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>sq0[a-z]{3}-[0-9A-Za-z\-_]{22})([^0-9A-Za-z]|$)
  filter_type: GeneralPattern
  use_ml: true
  validations:
    - SquareClientIdValidation
  required_substrings:
    - sq0
  min_line_len: 29
  usage_list:
    - src
    - doc

- name: Square OAuth Secret
  severity: high
  type: pattern
  values:
    - (?P<value>sq0csp-[0-9A-Za-z\-_]{43})
  filter_type: GeneralPattern
  use_ml: true
  validations: []
  required_substrings:
    - sq0csp
  min_line_len: 50
  usage_list:
    - src
    - doc

- name: Token
  severity: medium
  type: keyword
  values:
    - token
  filter_type: GeneralKeyword
  use_ml: true
  validations: []
  required_substrings:
    - token
  usage_list:
    - src

- name: Twilio API Key
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>SK[0-9a-fA-F]{32})([^0-9A-Za-z]|$)
  filter_type: GeneralPattern
  use_ml: true
  validations: []
  required_substrings:
    - SK
  min_line_len: 34
  usage_list:
    - src
    - doc

- name: URL Credentials
  severity: high
  type: pattern
  values:
    - //[^:]+(?P<separator>:)(?P<value>[^@]+)@
  filter_type: UrlCredentialsGroup
  use_ml: true
  validations: []
  required_substrings:
    - //
  min_line_len: 6
  usage_list:
    - src
    - doc

- name: Auth
  severity: medium
  type: keyword
  values:
    - auth(?!or)
  filter_type: GeneralKeyword
  use_ml: true
  validations: []
  required_substrings:
    - auth
  usage_list:
    - src

- name: Key
  severity: medium
  type: keyword
  values:
    - key(?!word)
  filter_type: GeneralKeyword
  use_ml: true
  validations: []
  required_substrings:
    - key
  usage_list:
    - src

- name: Telegram Bot API Token
  severity: high
  type: pattern
  values:
    - (?P<value>[0-9]{8,10}:[0-9A-Za-z_-]{35})
  filter_type: GeneralPattern
  use_ml: false
  validations: []
  required_substrings:
    - :AA
  min_line_len: 45
  usage_list:
    - src
    - doc

- name: PyPi API Token
  severity: high
  type: pattern
  values:
    - (?P<value>pypi-[\w_\-]{150,})
  filter_type: GeneralPattern
  use_ml: false
  validations: []
  required_substrings:
    - pypi
  min_line_len: 155
  usage_list:
    - src
    - doc

- name: Github Token
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>(ghr|gho|ghu|ghs)_[\w]{36,255})
  filter_type: GeneralPattern
  use_ml: false
  validations: []
  required_substrings:
    - gh
  min_line_len: 40
  usage_list:
    - src
    - doc

- name: Github Personal Access Token
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>ghp_[\w]{36,255})
  filter_type: GeneralPattern
  use_ml: false
  validations:
    - GithubTokenValidation
  required_substrings:
    - ghp_
  min_line_len: 40
  usage_list:
    - src
    - doc

- name: Github Fine-granted Token
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>github_pat_[0-9A-Za-z_]{80,255})
  filter_type: GeneralPattern
  use_ml: false
  validations:
    - GithubTokenValidation
  required_substrings:
    - github_pat_
  min_line_len: 90
  usage_list:
    - src
    - doc

- name: Firebase Domain
  severity: info
  type: pattern
  values:
    - (?P<value>[a-z0-9.-]+\.firebaseio\.com|[a-z0-9.-]+\.firebaseapp\.com)
  filter_type: GeneralPattern
  use_ml: false
  validations: []
  required_substrings:
    - firebase
  min_line_len: 16
  usage_list:
    - src
    - doc

- name: AWS S3 Bucket
  severity: info
  type: pattern
  values:
    - (?P<value>[a-z0-9.-]+\.s3\.amazonaws\.com|[a-z0-9.-]+\.s3-website[.-](eu|ap|us|ca|sa|cn))
  filter_type: GeneralPattern
  use_ml: false
  validations: []
  required_substrings:
    - s3-website
    - amazonaws
  min_line_len: 14
  usage_list:
    - src
    - doc

- name: Nonce
  severity: medium
  type: keyword
  values:
    - nonce
  filter_type: GeneralKeyword
  use_ml: true
  validations: []
  required_substrings:
    - nonce
  usage_list:
    - src

- name: Salt
  severity: medium
  type: keyword
  values:
    - salt
  filter_type: GeneralKeyword
  use_ml: true
  validations: []
  required_substrings:
    - salt
  usage_list:
    - src

- name: Certificate
  severity: medium
  type: keyword
  values:
    - cert
  filter_type: GeneralKeyword
  use_ml: true
  validations: []
  required_substrings:
    - cert
  usage_list:
    - src

- name: Azure Access Token
  severity: high
  type: pattern
  values:
    - (^|[^.0-9A-Za-z_/+-])(?P<value>eyJ[A-Za-z0-9_=-]{50,500}\.eyJ[A-Za-z0-9_=-]+\.[A-Za-z0-9_=-]+)
  filter_type: JWT
  validations: []
  use_ml: false
  required_substrings:
    - eyJ
  min_line_len: 148
  usage_list:
    - src
    - doc

- name: Azure Secret Value
  severity: high
  type: pattern
  values:
    -  (^|[^0-9A-Za-z_/+-])(?P<value>[a-zA-Z0-9_~.-]{3}8Q~[a-zA-Z0-9_~.-]{34})([^0-9A-Za-z+/_-]|$)
  filter_type: TokenPattern
  validations: []
  use_ml: false
  required_substrings:
    - 8Q~
  usage_list:
    - src
    - doc

- name: Bitbucket App Password
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>ATBB[A-Za-z0-9]{24}[A-F0-9]{8})([^0-9A-Za-z]|$)
  filter_type: StructuredToken
  validations: []
  use_ml: false
  required_substrings:
    - ATBB
  usage_list:
    - src
    - doc

- name: Bitbucket Repository Access Token
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>ATCTT3xFfGN0[a-zA-Z0-9-_]{171}=[A-F0-9]{8})([^0-9A-Za-z]|$)
  filter_type: TokenPattern
  use_ml: false
  required_substrings:
    - ATCTT3xFfGN0
  validations: []
  usage_list:
    - src
    - doc

- name: Bitbucket HTTP Access Token
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>BBDC-[NMO][ADgjQTwz][A-Za-z0-9+/]{42})([^0-9A-Za-z]|$)
  filter_type: StructuredToken
  use_ml: false
  validations: []
  required_substrings:
    - BBDC-
  usage_list:
    - src
    - doc

- name: Atlassian PAT token
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>ATATT3xFfGF0[a-zA-Z0-9-_]{171}=[A-F0-9]{8})([^0-9A-Za-z]|$)
  filter_type: TokenPattern
  use_ml: false
  validations: []
  required_substrings:
    - ATATT3xFfGF0
  usage_list:
    - src
    - doc

- name: Digital Ocean PAT
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z_/+-])(?P<value>dop_v1_[a-f0-9]{64})([^0-9A-Za-z+/_-]|$)
  filter_type: TokenPattern
  validations: []
  use_ml: false
  required_substrings:
    - dop_v1_
  usage_list:
    - src
    - doc

- name: Digital Ocean OAuth Access Token
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z_/+-])(?P<value>doo_v1_[a-f0-9]{64})([^0-9A-Za-z+/_-]|$)
  filter_type: TokenPattern
  validations: []
  use_ml: false
  required_substrings:
    - doo_v1_
  usage_list:
    - src
    - doc

- name: Dropbox OAuth2 API Access Token
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z])(?P<value>sl.[A-Za-z0-9_-]{135})([^0-9A-Za-z]|$)
  filter_type: TokenPattern
  validations: []
  use_ml: false
  required_substrings:
    - sl.
  usage_list:
    - src
    - doc

- name: NuGet API key
  severity: high
  type: pattern
  values:
    -  (^|[^0-9A-Za-z_/+-])(?P<value>oy2[a-z0-9]{43})([^0-9A-Za-z+/_-]|$)
  filter_type: TokenPattern
  validations: []
  use_ml: false
  required_substrings:
    - oy2
  usage_list:
    - src
    - doc

- name: Gitlab PAT
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z_/+-])(?P<value>glpat-[a-zA-Z0-9_-]{20})([^0-9A-Za-z+/_-]|$)
  filter_type: TokenPattern
  validations: []
  use_ml: false
  required_substrings:
    - glpat-
  usage_list:
    - src
    - doc

- name: Gitlab Pipeline Trigger Token
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z_/+-])(?P<value>glptt-[a-f0-9]{40})([^0-9A-Za-z+/_-]|$)
  filter_type: TokenPattern
  validations: []
  use_ml: false
  required_substrings:
    - glptt-
  usage_list:
    - src
    - doc

- name: Gitlab Registration Runner Token
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z_/+-])(?P<value>GR1348941[a-zA-Z0-9_-]{20})([^0-9A-Za-z+/_-]|$)
  filter_type: TokenPattern
  validations: []
  use_ml: false
  required_substrings:
    - GR1348941
  usage_list:
    - src
    - doc

- name: Gitlab Registration Runner Token 2023
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z_/+-])(?P<value>glrt-[a-zA-Z0-9_-]{20})([^0-9A-Za-z+/_-]|$)
  filter_type: TokenPattern
  validations: []
  use_ml: false
  required_substrings:
    - glrt-
  usage_list:
    - src
    - doc

- name: Grafana Provisioned API Key
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z_/+-])(?P<value>eyJ[a-zA-Z0-9=/-]{64,360})([^0-9A-Za-z+/_-]|$)
  filter_type: Grafana
  validations: []
  use_ml: false
  required_substrings:
    - eyJ
  usage_list:
    - src
    - doc

- name: Grafana Access Policy Token
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z_/+-])(?P<value>glc_eyJ[a-zA-Z0-9=/-]{80,360})([^0-9A-Za-z+/_-]|$)
  filter_type: Grafana
  validations: []
  use_ml: false
  required_substrings:
    - glc_eyJ
  usage_list:
    - src
    - doc

- name: Dropbox API secret (long term)
  severity: high
  type: pattern
  values:
    -  (^|[^0-9A-Za-z])(?=[A-Za-z0-9]{64})(?P<value>[A-Za-z0-9]{10,12}[B-Za-z0-9]A{10,12}[B-Za-z0-9][A-Za-z0-9]{40,44})([^0-9A-Za-z_/-]|$)
  filter_type:
  validations: []
  use_ml: false
  required_substrings:
    - AAAAAAAAAA
  usage_list:
    - src
    - doc

- name: Bitbucket Client ID
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z.$_/+-])(?P<value>([a-zA-Z0-9]{18})|[a-zA-Z0-9]{32})([^0-9A-Za-z.$_/+-]|$)
  filter_type: TokenPattern
  use_ml: false
  validations: []
  usage_list:
    - src
    - doc

- name: Bitbucket Client Secret
  severity: medium
  type: pattern
  values:
    - (^|[^0-9A-Za-z.$_/+-])(?P<value>[a-zA-Z0-9_-]{32}([a-zA-Z0-9_-]{32})?)([^0-9A-Za-z.$_/+-]|$)
  validations: []
  filter_type: TokenPattern
  use_ml: true
  usage_list:
    - src
    - doc

- name: Dropbox App secret
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z_/+-])(?P<value>[a-z0-9]{15})([^0-9A-Za-z+/_-]|$)
  filter_type: TokenBase32
  validations: []
  use_ml: false
  min_line_len: 15
  usage_list:
    - src
    - doc

- name: Gitlab Feed Token
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z._/+-])(?P<value>[a-zA-Z0-9_-]{20})([^0-9A-Za-z+/_-]|$)
  filter_type: TokenPattern
  validations: []
  use_ml: true
  usage_list:
    - src
    - doc

- name: Gitlab Incoming Email Token
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z._/+-])(?P<value>[a-z0-9]{25})([^0-9A-Za-z+/_-]|$)
  filter_type: TokenPattern
  validations: []
  use_ml: false
  usage_list:
    - src
    - doc

- name: Jira 2FA
  severity: high
  type: pattern
  values:
    - (^|[^0-9A-Za-z_/+-])(?P<value>[A-Z2-7]{16})([^0-9A-Za-z_/+-]|$)
  filter_type: TokenBase32
  use_ml: false
  validations: []
  usage_list:
    - src
    - doc

